theme:           jekyll-theme-cayman
title:           Pong
description:     Remake of the classic game with customization options for adding variety
is_user_page:    false
is_project_page: true
show_downloads:  true
